# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: # это описание события, по которому будет запускаться наш скрипт.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    # эта часть кода отвечает за запуск workflow при каждом пуше и пуле
jobs:
  build: # построение проекта

    runs-on: ubuntu-latest # на какой ОС запускать

    steps: 
    - uses: actions/checkout@v2 # позволяет переиспользовать другие экшены
    - name: Set up Python 3.8 # название "шага" (этапа) работы. 
      uses: actions/setup-python@v2
      with: # При помощи with мы можем указать параметры с которыми запускаем действие,
        python-version: 3.8 # "Используя python3.8 сделай следующее
    - name: Install dependencies
      run: | # запускай/выполни
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install django==3
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi # можно так же задавать условия
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
